### ISSUE TITLE
予約一覧エリアをスクロール可能にする

### ISSUE THREAD

**Issue by k-wakatake** [k-wakatake/meeting-room-reservation#1]
## 概要
予約件数が多くなった場合に、予約一覧の表示領域が長くなりすぎて画面全体のユーザビリティが低下する問題があります。予約一覧エリアに固定高さを設定し、内容がオーバーフローした場合にスクロール可能にする機能を追加する必要があります。

## 現状の問題点
現在の実装では、予約が増えると予約一覧（`#reservations`）の高さが無制限に伸びていき、以下の問題が発生します：
- ページが非常に長くなり、全体のスクロールが煩雑になる
- 予約フォームとCSVダウンロードボタンの間の距離が広がりすぎる
- モバイル表示時にページ全体の使いやすさが低下する

## 対応内容
1. 予約一覧コンテナ（`#reservations`）に最大高さを設定する
2. コンテンツがオーバーフローした場合にスクロールバーを表示する
3. スクロールバーのスタイルをUIデザインに合わせて調整する

## 参照コード
該当箇所は以下の部分です：

```html
<div class="reservation-list">
    <h2>予約一覧</h2>
    <div id="reservations"></div>
    <button id="download-csv" class="btn-download">CSVダウンロード</button>
</div>
```

## 技術的な実装案
CSSで以下のような変更を加える：
```css
#reservations {
    max-height: 400px; /* または適切な高さ */
    overflow-y: auto;
    margin-bottom: 25px;
}
```

## 期待される結果
- 予約が多数ある場合も、予約一覧セクションの高さが一定に保たれる
- 予約一覧内でスクロールすることで、すべての予約を確認できる
- ページ全体のレイアウトバランスが保たれる

## 優先度
中：ユーザビリティの向上につながる機能改善
